#ifndef FT_MATRIX_PRELUDE_H
#define FT_MATRIX_PRELUDE_H

#define FT_MATRIX_TARGET_CODE_NONE 0L
#define FT_MATRIX_TARGET_CODE_SSE 386101000L
#define FT_MATRIX_TARGET_CODE_SSE2 386102000L
#define FT_MATRIX_TARGET_CODE_SSE3 386103000L
#define FT_MATRIX_TARGET_CODE_SSSE3 386103001L
#define FT_MATRIX_TARGET_CODE_SSE4_1 386104001L
#define FT_MATRIX_TARGET_CODE_SSE4_2 386104002L
#define FT_MATRIX_TARGET_CODE_AVX 386201000L
#define FT_MATRIX_TARGET_CODE_AVX2 386202000L
#define FT_MATRIX_TARGET_CODE_AVX512 386203000L
#define FT_MATRIX_TARGET_CODE_ARMV7A 1007000000L
#define FT_MATRIX_TARGET_CODE_ARMV8A 1008000000L
#define FT_MATRIX_TARGET_CODE_ARMV8_1A 1008001000L
#define FT_MATRIX_TARGET_CODE_ARMV8_2A 1008002000L
#define FT_MATRIX_TARGET_CODE_ARMV8_3A 1008003000L
#define FT_MATRIX_TARGET_CODE_ARMV8_4A 1008004000L
#define FT_MATRIX_TARGET_CODE_ARMV8_5A 1008005000L
#define FT_MATRIX_TARGET_CODE_ARMV8_6A 1008006000L
#define FT_MATRIX_TARGET_CODE_ARMV9_0A 1009000000L
#define FT_MATRIX_TARGET_CODE_ARMV9_2A 1009002000L


#ifdef FT_MATRIX_TARGET
# error FT_MATRIX_TARGET is already defined
#endif


#ifdef FT_MATRIX_TARGET_NONE
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_NONE
#endif

#ifdef FT_MATRIX_TARGET_SSE
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_SSE
#endif

#ifdef FT_MATRIX_TARGET_SSE2
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_SSE2
#endif

#ifdef FT_MATRIX_TARGET_SSE3
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_SSE3
#endif

#ifdef FT_MATRIX_TARGET_SSSE3
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_SSSE3
#endif

#ifdef FT_MATRIX_TARGET_SSE4_1
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_SSE4_1
#endif

#ifdef FT_MATRIX_TARGET_SSE4_2
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_SSE4_2
#endif

#ifdef FT_MATRIX_TARGET_AVX
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_AVX
#endif

#ifdef FT_MATRIX_TARGET_AVX2
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_AVX2
#endif

#ifdef FT_MATRIX_TARGET_AVX512
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_AVX512
#endif

#ifdef FT_MATRIX_TARGET_ARMV7A
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_ARMV7A
#endif

#ifdef FT_MATRIX_TARGET_ARMV8A
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_ARMV8A
#endif

#ifdef FT_MATRIX_TARGET_ARMV8_1A
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_ARMV8_1A
#endif

#ifdef FT_MATRIX_TARGET_ARMV8_2A
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_ARMV8_2A
#endif

#ifdef FT_MATRIX_TARGET_ARMV8_3A
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_ARMV8_3A
#endif

#ifdef FT_MATRIX_TARGET_ARMV8_4A
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_ARMV8_4A
#endif

#ifdef FT_MATRIX_TARGET_ARMV8_5A
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_ARMV8_5A
#endif

#ifdef FT_MATRIX_TARGET_ARMV8_6A
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_ARMV8_6A
#endif

#ifdef FT_MATRIX_TARGET_ARMV9_0A
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_ARMV9_0A
#endif

#ifdef FT_MATRIX_TARGET_ARMV9_2A
# ifdef FT_MATRIX_TARGET
#  error FT_MATRIX_TARGET_* is given more than once
# endif
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_ARMV9_2A
#endif


#ifndef FT_MATRIX_TARGET
# define FT_MATRIX_TARGET FT_MATRIX_TARGET_CODE_NONE
#endif

#endif
